general:
  model_path: data/valuation_model.yml
  log_path: .infinium.log
database:
  dialect: postgresql
  driver: psycopg2
  username: jgenson
  password: 9eNtHpG3!@#
  host: localhost
  port: 5432
  database: infinium
  echo: False
sgd_classifier:
  loss: hinge
  penalty: l2
  alpha: 0.0001
  l1_ratio: 0.15
  fit_intercept: True
  n_iter: 5
  shuffle: False
  verbose: False
  n_jobs: 1
  learning_rate: optimal
  eta0: 0.0
  power_t: 0.5
