general:
  database_type: pgsql
  database_path: data/stock_data.yml
  model_path: data/valuation_model.yml
  log_path: .infinium.log
sgd_classifier:
  loss: hinge
  penalty: l2
  alpha: 0.0001
  l1_ratio: 0.15
  fit_intercept: True
  n_iter: 5
  shuffle: False
  verbose: False
  n_jobs: 1
  learning_rate: optimal
  eta0: 0.0
  power_t: 0.5